
bible_books = {
    185: "The First Book of Moses: Called Genesis",
    5389: "The Second Book of Moses: Called Exodus",
    9709: "The Third Book of Moses: Called Leviticus",
    12882: "The Fourth Book of Moses: Called Numbers",
    17402: "The Fifth Book of Moses: Called Deuteronomy",
    21005: "The Book of Joshua",
    23473: "The Book of Judges",
    25855: "The Book of Ruth",
    26190: "The First Book of Samuel, otherwise called the First Book of the Kings",
    29324: "The Second Book of Samuel, otherwise called the Second Book of the Kings",
    31945: "The First Book of the Kings, commonly called the Third Book of the Kings",
    35035: "The Second Book of the Kings, commonly called the Fourth Book of the Kings",
    37881: "The First Book of the Chronicles",
    40947: "The Second Book of the Chronicles",
    44237: "Ezra",
    45259: "The Book of Nehemiah",
    46710: "The Book of Esther",
    47413: "The Book of Job",
    50585: "The Book of Psalms",
    57931: "The Proverbs",
    60639: "Ecclesiastes, or, The Preacher",
    61417: "The Song of Solomon",
    61814: "The Book of the Prophet Isaiah",
    66637: "The Book of the Prophet Jeremiah",
    71963: "The Lamentations of Jeremiah",
    72469: "The Book of the Prophet Ezekiel",
    77372: "The Book of Daniel",
    78828: "Hosea",
    79540: "Joel",
    79816: "Amos",
    80380: "Obadiah",
    80473: "Jonah",
    80655: "Micah",
    81064: "Nahum",
    81256: "Habakkuk",
    81473: "Zephaniah",
    81689: "Haggai",
    81843: "Zechariah",
    82662: "Malachi",
    82895: "The Gospel According to Saint Matthew",
    86353: "The Gospel According to Saint Mark",
    88536: "The Gospel According to Saint Luke",
    92289: "The Gospel According to Saint John",
    95062: "The Acts of the Apostles",
    98497: "The Epistle of Paul the Apostle to the Romans",
    99909: "The First Epistle of Paul the Apostle to the Corinthians",
    101300: "The Second Epistle of Paul the Apostle to the Corinthians",
    102173: "The Epistle of Paul the Apostle to the Galatianss",
    102655: "The Epistle of Paul the Apostle to the Ephesians",
    103145: "The Epistle of Paul the Apostle to the Philippians",
    103479: "The Epistle of Paul the Apostle to the Colossians",
    103795: "The First Epistle of Paul the Apostle to the Thessalonians",
    104090: "The Second Epistle of Paul the Apostle to the Thessalonians",
    104257: "The First Epistle of Paul the Apostle to Timothy",
    104629: "The Second Epistle of Paul the Apostle to Timothy",
    104905: "The Epistle of Paul the Apostle to Titus",
    105065: "The Epistle of Paul the Apostle to Philemon",
    105147: "The Epistle of Paul the Apostle to the Hebrews",
    106169: "The General Epistle of James",
    106526: "The First Epistle General of Peter",
    106892: "The Second General Epistle of Peter",
    107130: "The First Epistle General of John",
    107492: "The Second Epistle General of John",
    107544: "The Third Epistle General of John",
    107599: "The General Epistle of Jude",
    107700: "The Revelation of Saint John the Devine"
}

iching = {
    1: """1. <span style="font-family: iching;">䷀</span> CH'IEN / THE CREATIVE""",
    2: """2. <span style="font-family: iching;">䷁</span> K'UN / THE RECEPTIVE, EARTH""",
    3: """3. <span style="font-family: iching;">䷂</span> CHUN / DIFFICULTY AT THE BEGINNING""",
    4: """4. <span style="font-family: iching;">䷃</span> MÊNG / YOUTHFUL FOLLY""",
    5: """5. <span style="font-family: iching;">䷄</span> HSÜ / WAITING (NOURISHMENT)""",
    6: """6. <span style="font-family: iching;">䷅</span> SUNG / CONFLICT""",
    7: """7. <span style="font-family: iching;">䷆</span> SHIH / THE ARMY""",
    8: """8. <span style="font-family: iching;">䷇</span> PI / HOLDING TOGETHER (UNION)""",
    9: """9. <span style="font-family: iching;">䷈</span> HSIAO CH'U / THE TAMING POWER OF THE SMALL""",
    10: """10. <span style="font-family: iching;">䷉</span> LÜ / TREADING (CONDUCT)""",
    11: """11. <span style="font-family: iching;">䷊</span> T'AI / PEACE""",
    12: """12. <span style="font-family: iching;">䷋</span> P'I / STANDSTILL (STAGNATION)""",
    13: """13. <span style="font-family: iching;">䷌</span> T'UNG JÊN / FELLOWSHIP WITH MEN""",
    14: """14. <span style="font-family: iching;">䷍</span> TA YU / POSSESSION IN GREAT MEASURE""",
    15: """15. <span style="font-family: iching;">䷎</span> CH'IEN / MODESTY""",
    16: """16. <span style="font-family: iching;">䷏</span> YÜ / ENTHUSIASM""",
    17: """17. <span style="font-family: iching;">䷐</span> SUI / FOLLOWING""",
    18: """18. <span style="font-family: iching;">䷑</span> KU / WORK ON WHAT HAS BEEN SPOILED (DECAY)""",
    19: """19. <span style="font-family: iching;">䷒</span> LIN / APPROACH""",
    20: """20. <span style="font-family: iching;">䷓</span> KUAN / CONTEMPLATION (VIEW)""",
    21: """21. <span style="font-family: iching;">䷔</span> SHIH HO / BITING THROUGH""",
    22: """22. <span style="font-family: iching;">䷕</span> PI / GRACE""",
    23: """23. <span style="font-family: iching;">䷖</span> PO / SPLITTING APART""",
    24: """24. <span style="font-family: iching;">䷗</span> FU / RETURN (THE TURNING POINT)""",
    25: """25. <span style="font-family: iching;">䷘</span> WU WANG / INNOCENCE (THE UNEXPECTED)""",
    26: """26. <span style="font-family: iching;">䷙</span> TA CH'U / THE TAMING POWER OF THE GREAT""",
    27: """27. <span style="font-family: iching;">䷚</span> I / CORNERS OF THE MOUTH (PROVIDING NOURISHMENT)""",
    28: """28. <span style="font-family: iching;">䷛</span> TA KUO / PREPONDERANCE OF THE GREAT""",
    29: """29. <span style="font-family: iching;">䷜</span> K'AN / THE ABYSMAL (WATER)""",
    30: """30. <span style="font-family: iching;">䷝</span> LI / THE CLINGING, FIRE""",
    31: """31. <span style="font-family: iching;">䷞</span> HSIEN / INFLUENCE (WOOING)""",
    32: """32. <span style="font-family: iching;">䷟</span> HÊNG / DURATION""",
    33: """33. <span style="font-family: iching;">䷠</span> TUN / RETREAT""",
    34: """34. <span style="font-family: iching;">䷡</span> TA CHUANG / THE POWER OF THE GREAT""",
    35: """35. <span style="font-family: iching;">䷢</span> CHIN / PROGRESS""",
    36: """36. <span style="font-family: iching;">䷣</span> MING I / DARKENING OF THE LIGHT""",
    37: """37. <span style="font-family: iching;">䷤</span> CHIA JÊN / THE FAMILY (THE CLAN)""",
    38: """38. <span style="font-family: iching;">䷥</span> K'UEI / OPPOSITION""",
    39: """39. <span style="font-family: iching;">䷦</span> CHIEN / OBSTRUCTION""",
    40: """40. <span style="font-family: iching;">䷧</span> HSIEH / DELIVERANCE""",
    41: """41. <span style="font-family: iching;">䷨</span> SUN / DECREASE""",
    42: """42. <span style="font-family: iching;">䷩</span> I / INCREASE""",
    43: """43. <span style="font-family: iching;">䷪</span> KUAI / BREAK-THROUGH (RESOLUTENESS)""",
    44: """44. <span style="font-family: iching;">䷫</span> KOU / COMING TO MEET""",
    45: """45. <span style="font-family: iching;">䷬</span> TS'UI / GATHERING TOGETHER (MASSING)""",
    46: """46. <span style="font-family: iching;">䷭</span> SHÊNG / PUSHING UPWARD""",
    47: """47. <span style="font-family: iching;">䷮</span> K'UN / OPPRESSION (EXHAUSTION)""",
    48: """48. <span style="font-family: iching;">䷯</span> CHING / THE WELL""",
    49: """49. <span style="font-family: iching;">䷰</span> KO / REVOLUTION (MOLTING)""",
    50: """50. <span style="font-family: iching;">䷱</span> TING / THE CALDRON""",
    51: """51. <span style="font-family: iching;">䷲</span> CHÊN / THE AROUSING (SHOCK, THUNDER)""",
    52: """52. <span style="font-family: iching;">䷳</span> KÊN / KEEPING STILL, MOUNTAIN""",
    53: """53. <span style="font-family: iching;">䷴</span> CHIEN / DEVELOPMENT (GRADUAL PROGRESS)""",
    54: """54. <span style="font-family: iching;">䷵</span> KUEI MEI / THE MARRYING MAIDEN""",
    55: """55. <span style="font-family: iching;">䷶</span> FÊNG / ABUNDANCE (FULLNESS)""",
    56: """56. <span style="font-family: iching;">䷷</span> LÜ / THE WANDERER""",
    57: """57. <span style="font-family: iching;">䷸</span> SUN / THE GENTLE (THE PENETRATING, WIND)""",
    58: """58. <span style="font-family: iching;">䷹</span> TUI / THE JOYOUS, LAKE""",
    59: """59. <span style="font-family: iching;">䷺</span> HUAN / DISPERSION (DISSOLUTION)""",
    60: """60. <span style="font-family: iching;">䷻</span> CHIEH / LIMITATION""",
    61: """61. <span style="font-family: iching;">䷼</span> CHUNG FU / INNER TRUTH""",
    62: """62. <span style="font-family: iching;">䷽</span> HSIAO KUO / PREPONDERANCE OF THE SMALL""",
    63: """63. <span style="font-family: iching;">䷾</span> CHI CHI / AFTER COMPLETION""",
    64: """64. <span style="font-family: iching;">䷿</span> WEI CHI / BEFORE COMPLETION"""
}

list_8ball = [
    "It is certain",
    "It is decidedly so",
    "Without a doubt",
    "Yes – definitely",
    "You may rely on it",
    "As I see it, yes",
    "Most likely",
    "Outlook good",
    "Yes",
    "Signs point to yes",
    "Reply hazy, try again",
    "Ask again later",
    "Better not tell you now",
    "Cannot predict now",
    "Concentrate and ask again",
    "Don't count on it",
    "My reply is no",
    "My sources say no",
    "Outlook not so good",
    "Very doubtful"
]

runes = [
    # ELDER FUTHARK RUNE ALPHABET WITHOUT BLANK
    ("""<span style="font-family: runes;">ᚠ</span> - FEHU (WEALTH)""", """<span style="font-family: runes;">ᚠ</span> - FEHU Rev. (LOSS)"""),
    ("""<span style="font-family: runes;">ᚢ</span> - URUZ (STRENGTH)""", """<span style="font-family: runes;">ᚢ</span> - URUZ Rev. (WEAKNESS)"""),
    ("""<span style="font-family: runes;">ᚦ</span> - THURISAZ (PROTECTION)""", """<span style="font-family: runes;">ᚦ</span> - THURISAZ Rev. (STUBBORN)"""),
    ("""<span style="font-family: runes;">ᚨ</span> - ANSUZ (WISDOM)""", """<span style="font-family: runes;">ᚨ</span> - ANSUZ Rev. (TRICKERY)"""),
    ("""<span style="font-family: runes;">ᚱ</span> - RAIDO (JOURNEY)""", """<span style="font-family: runes;">ᚱ</span> - RAIDO Rev. (CRISIS OR STANDSTILL)""",),
    ("""<span style="font-family: runes;">ᚲ</span> - KAUNA (TORCH)""", """<span style="font-family: runes;">ᚲ</span> - KAUNA Rev. (WITHDRAWAL)"""),
    ("""<span style="font-family: runes;">ᚷ</span> - GEBO (MARRIAGE)""", """<span style="font-family: runes;">ᚷ</span> - GEBO (MARRIAGE)"""),
    ("""<span style="font-family: runes;">ᚹ</span> - WUNJO (JOY)""", """<span style="font-family: runes;">ᚹ</span> - WUNJO Rev. (SORROW)"""),
    ("""<span style="font-family: runes;">ᚺ</span> - HAGLAZ (DISRUPTION)""", """<span style="font-family: runes;">ᚺ</span> - HAGLAZ (DISRUPTION)"""),
    ("""<span style="font-family: runes;">ᚾ</span> - NAUDIZ (CONSTRAINT)""", """<span style="font-family: runes;">ᚾ</span> - NAUDIZ Rev. (IMPROPER COURSE OF ACTION)"""),
    ("""<span style="font-family: runes;">ᛁ</span> - ISA (STANDSTILL)""", """<span style="font-family: runes;">ᛁ</span> - ISA (STANDSTILL)"""),
    ("""<span style="font-family: runes;">ᛃ</span> - JERA (SUCCESS)""", """<span style="font-family: runes;">ᛃ</span> - JERA (SUCCESS)"""),
    ("""<span style="font-family: runes;">ᛇ</span> - IWAZ (SAFETY)""", """<span style="font-family: runes;">ᛇ</span> - IWAZ (SAFETY)"""),
    ("""<span style="font-family: runes;">ᛈ</span> - PERTHO (CHANCE AND BECOMING)""", """<span style="font-family: runes;">ᛈ</span> - PERTHO Rev. (EVENTS STALLED)"""),
    ("""<span style="font-family: runes;">ᛉ</span> - ALGIZ (FRIENDSHIP)""", """<span style="font-family: runes;">ᛉ</span> - ALGIZ Rev. (VULNERABILITY)"""),
    ("""<span style="font-family: runes;">ᛋ</span> - SOWILO (SELF)""", """<span style="font-family: runes;">ᛋ</span> - SOWILO (SELF)"""),
    ("""<span style="font-family: runes;">ᛏ</span> - TIWAZ (VICTORY)""", """<span style="font-family: runes;">ᛏ</span> - TIWAZ Rev. (LOW ENERGY, COWARDICE)"""),
    ("""<span style="font-family: runes;">ᛒ</span> - BERKANAN (LOVE)""", """<span style="font-family: runes;">ᛒ</span> - BERKANAN Rev. (UNFORTUNATE DOMESTIC SITUATION)"""),
    ("""<span style="font-family: runes;">ᛖ</span> - EHWAZ (TRUST)""", """<span style="font-family: runes;">ᛖ</span> - EHWAZ Rev. (SUDDEN UNWANTED CHANGE)"""),
    ("""<span style="font-family: runes;">ᛗ</span> - MANNAZ (HUMANITY)""", """<span style="font-family: runes;">ᛗ</span> - MANNAZ (ENEMY)"""),
    ("""<span style="font-family: runes;">ᛚ</span> - LAGUZ (HEALING)""", """<span style="font-family: runes;">ᛚ</span> - LAGUZ Rev. (BLOCKED HELP)"""),
    ("""<span style="font-family: runes;">ᛝ</span> - INGUZ (FERTILITY)""", """<span style="font-family: runes;">ᛝ</span> - INGUZ (FERTILITY)"""),
    ("""<span style="font-family: runes;">ᛟ</span> - OTHILA (STABLE PROSPERITY)""", """<span style="font-family: runes;">ᛟ</span> - OTHILA Rev. (DISOWNMENT, STUCK IN OLD IDEAS)"""),
    ("""<span style="font-family: runes;">ᛞ</span> - DAGAZ (HOME)""", """<span style="font-family: runes;">ᛞ</span> - DAGAZ (HOME)""")
]

runes_b = [
    # ELDER FUTHARK RUNE ALPHABET WITH BLANK
    ("""<span style="font-family: runes;">ᚠ</span> - FEHU (WEALTH)""", """<span style="font-family: runes;">ᚠ</span> - FEHU Rev. (LOSS)"""),
    ("""<span style="font-family: runes;">ᚢ</span> - URUZ (STRENGTH)""", """<span style="font-family: runes;">ᚢ</span> - URUZ Rev. (WEAKNESS)"""),
    ("""<span style="font-family: runes;">ᚦ</span> - THURISAZ (PROTECTION)""", """<span style="font-family: runes;">ᚦ</span> - THURISAZ Rev. (STUBBORN)"""),
    ("""<span style="font-family: runes;">ᚨ</span> - ANSUZ (WISDOM)""", """<span style="font-family: runes;">ᚨ</span> - ANSUZ Rev. (TRICKERY)"""),
    ("""<span style="font-family: runes;">ᚱ</span> - RAIDO (JOURNEY)""", """<span style="font-family: runes;">ᚱ</span> - RAIDO Rev. (CRISIS OR STANDSTILL)"""),
    ("""<span style="font-family: runes;">ᚲ</span> - KAUNA (TORCH)""", """<span style="font-family: runes;">ᚲ</span> - KAUNA Rev. (WITHDRAWAL)"""),
    ("""<span style="font-family: runes;">ᚷ</span> - GEBO (MARRIAGE)""", """<span style="font-family: runes;">ᚷ</span> - GEBO (MARRIAGE)"""),
    ("""<span style="font-family: runes;">ᚹ</span> - WUNJO (JOY)""", """<span style="font-family: runes;">ᚹ</span> - WUNJO Rev. (SORROW)"""),
    ("""<span style="font-family: runes;">ᚺ</span> - HAGLAZ (DISRUPTION)""", """<span style="font-family: runes;">ᚺ</span> - HAGLAZ (DISRUPTION)"""),
    ("""<span style="font-family: runes;">ᚾ</span> - NAUDIZ (CONSTRAINT)""", """<span style="font-family: runes;">ᚾ</span> - NAUDIZ Rev. (IMPROPER COURSE OF ACTION)"""),
    ("""<span style="font-family: runes;">ᛁ</span> - ISA (STANDSTILL)""", """<span style="font-family: runes;">ᛁ</span> - ISA (STANDSTILL)"""),
    ("""<span style="font-family: runes;">ᛃ</span> - JERA (SUCCESS)""", """<span style="font-family: runes;">ᛃ</span> - JERA (SUCCESS)"""),
    ("""<span style="font-family: runes;">ᛇ</span> - IWAZ (SAFETY)""", """<span style="font-family: runes;">ᛇ</span> - IWAZ (SAFETY)"""),
    ("""<span style="font-family: runes;">ᛈ</span> - PERTHO (CHANCE AND BECOMING)""", """<span style="font-family: runes;">ᛈ</span> - PERTHO Rev. (EVENTS STALLED)"""),
    ("""<span style="font-family: runes;">ᛉ</span> - ALGIZ (FRIENDSHIP)""", """<span style="font-family: runes;">ᛉ</span> - ALGIZ Rev. (VULNERABILITY)"""),
    ("""<span style="font-family: runes;">ᛋ</span> - SOWILO (SELF)""", """<span style="font-family: runes;">ᛋ</span> - SOWILO (SELF)"""),
    ("""<span style="font-family: runes;">ᛏ</span> - TIWAZ (VICTORY)""", """<span style="font-family: runes;">ᛏ</span> - TIWAZ Rev. (LOW ENERGY, COWARDICE)"""),
    ("""<span style="font-family: runes;">ᛒ</span> - BERKANAN (LOVE)""", """<span style="font-family: runes;">ᛒ</span> - BERKANAN Rev. (UNFORTUNATE DOMESTIC SITUATION)"""),
    ("""<span style="font-family: runes;">ᛖ</span> - EHWAZ (TRUST)""", """<span style="font-family: runes;">ᛖ</span> - EHWAZ Rev. (SUDDEN UNWANTED CHANGE)"""),
    ("""<span style="font-family: runes;">ᛗ</span> - MANNAZ (HUMANITY)""", """<span style="font-family: runes;">ᛗ</span> - MANNAZ (ENEMY)"""),
    ("""<span style="font-family: runes;">ᛚ</span> - LAGUZ (HEALING)""", """<span style="font-family: runes;">ᛚ</span> - LAGUZ Rev. (BLOCKED HELP)"""),
    ("""<span style="font-family: runes;">ᛝ</span> - INGUZ (FERTILITY)""", """<span style="font-family: runes;">ᛝ</span> - INGUZ (FERTILITY)"""),
    ("""<span style="font-family: runes;">ᛟ</span> - OTHILA (STABLE PROSPERITY)""", """<span style="font-family: runes;">ᛟ</span> - OTHILA Rev. (DISOWNMENT, STUCK IN OLD IDEAS)"""),
    ("""<span style="font-family: runes;">ᛞ</span> - DAGAZ (HOME)""", """<span style="font-family: runes;">ᛞ</span> - DAGAZ (HOME)"""),
    ("""<span style="font-family: runes;">□</span> - BLANK (DESTINY)""", """<span style="font-family: runes;">□</span> - BLANK (DESTINY)""")
]

tarot = [
    # 78 CARDS IN A DECK, 156 POSSIBILITIES WHEN UPSIDE DOWN CARDS ARE INCLUDED

    # MAJOR ARCANA
    ("The Fool", "The Fool (↓)"),
    ("The Magician", "The Magician (↓)"),
    ("The High Priestess", "The High Priestess (↓)"),
    ("The Empress", "The Empress (↓)"),
    ("The Emperor", "The Emperor (↓)"),
    ("The Hierophant", "The Hierophant (↓)"),
    ("The Lovers", "The Lovers (↓)"),
    ("The Chariot", "The Chariot (↓)"),
    ("Strength", "Strength (↓)"),
    ("The Hermit", "The Hermit (↓)"),
    ("Wheel of Fortune", "Wheel of Fortune (↓)"),
    ("Justice", "Justice (↓)"),
    ("The Hanged Man", "The Hanged Man (↓)"),
    ("Death", "Death (↓)"),
    ("Temperance", "Temperance (↓)"),
    ("The Devil", "The Devil (↓)"),
    ("The Tower", "The Tower (↓)"),
    ("The Star", "The Star (↓)"),
    ("The Moon", "The Moon (↓)"),
    ("The Sun", "The Sun (↓)"),
    ("Judgement", "Judgement (↓)"),
    ("The World", "The World (↓)"),

    #Wands
    ("Ace of Wands", "Ace of Wands (↓)"),
    ("Two of Wands", "Two of Wands (↓)"),
    ("Three of Wands", "Three of Wands (↓)"),
    ("Four of Wands", "Four of Wands (↓)"),
    ("Five of Wands", "Five of Wands (↓)"),
    ("Six of Wands", "Six of Wands (↓)"),
    ("Seven of Wands", "Seven of Wands (↓)"),
    ("Eight of Wands", "Eight of Wands (↓)"),
    ("Nine of Wands", "Nine of Wands (↓)"),
    ("Ten of Wands", "Ten of Wands (↓)"),
    ("Page of Wands", "Page of Wands (↓)"),
    ("Knight of Wands", "Knight of Wands (↓)"),
    ("Queen of Wands", "Queen of Wands (↓)"),
    ("King of Wands", "King of Wands (↓)"),

    #Cups
    ("Ace of Cups", "Ace of Cups (↓)"),
    ("Two of Cups", "Two of Cups (↓)"),
    ("Three of Cups", "Three of Cups (↓)"),
    ("Four of Cups", "Four of Cups (↓)"),
    ("Five of Cups", "Five of Cups (↓)"),
    ("Six of Cups", "Six of Cups (↓)"),
    ("Seven of Cups", "Seven of Cups (↓)"),
    ("Eight of Cups", "Eight of Cups (↓)"),
    ("Nine of Cups", "Nine of Cups (↓)"),
    ("Ten of Cups", "Ten of Cups (↓)"),
    ("Page of Cups", "Page of Cups (↓)"),
    ("Knight of Cups", "Knight of Cups (↓)"),
    ("Queen of Cups", "Queen of Cups (↓)"),
    ("King of Cups", "King of Cups (↓)"),

    #Swords
    ("Ace of Swords", "Ace of Swords (↓)"),
    ("Two of Swords", "Two of Swords (↓)"),
    ("Three of Swords", "Three of Swords (↓)"),
    ("Four of Swords", "Four of Swords (↓)"),
    ("Five of Swords", "Five of Swords (↓)"),
    ("Six of Swords", "Six of Swords (↓)"),
    ("Seven of Swords", "Seven of Swords (↓)"),
    ("Eight of Swords", "Eight of Swords (↓)"),
    ("Nine of Swords", "Nine of Swords (↓)"),
    ("Ten of Swords", "Ten of Swords (↓)"),
    ("Page of Swords", "Page of Swords (↓)"),
    ("Knight of Swords", "Knight of Swords (↓)"),
    ("Queen of Swords", "Queen of Swords (↓)"),
    ("King of Swords", "King of Swords (↓)"),

    # COINS
    ("Ace of Coins", "Ace of Coins (↓)"),
    ("Two of Coins", "Two of Coins (↓)"),
    ("Three of Coins", "Three of Coins (↓)"),
    ("Four of Coins", "Four of Coins (↓)"),
    ("Five of Coins", "Five of Coins (↓)"),
    ("Six of Coins", "Six of Coins (↓)"),
    ("Seven of Coins", "Seven of Coins (↓)"),
    ("Eight of Coins", "Eight of Coins (↓)"),
    ("Nine of Coins", "Nine of Coins (↓)"),
    ("Ten of Coins", "Ten of Coins (↓)"),
    ("Page of Coins", "Page of Coins (↓)"),
    ("Knight of Coins", "Knight of Coins (↓)"),
    ("Queen of Coins", "Queen of Coins (↓)"),
    ("King of Coins", "King of Coins (↓)")
]

tarot_c = [
    # 78 CARDS IN A DECK, 156 POSSIBILITIES WHEN UPSIDE DOWN CARDS ARE INCLUDED

    # MAJOR ARCANA
    ("The Fool", "The Fool (↓)"),
    ("The Magician", "The Magician (↓)"),
    ("The High Priestess", "The High Priestess (↓)"),
    ("The Empress", "The Empress (↓)"),
    ("The Emperor", "The Emperor (↓)"),
    ("The Hierophant", "The Hierophant (↓)"),
    ("The Lovers", "The Lovers (↓)"),
    ("The Chariot", "The Chariot (↓)"),
    ("Lust", "Lust (↓)"),
    ("The Hermit", "The Hermit (↓)"),
    ("Fortune", "Fortune (↓)"),
    ("Adjustment", "Adjustment (↓)"),
    ("The Hanged Man", "The Hanged Man (↓)"),
    ("Death", "Death (↓)"),
    ("Art", "Art (↓)"),
    ("The Devil", "The Devil (↓)"),
    ("The Tower", "The Tower (↓)"),
    ("The Star", "The Star (↓)"),
    ("The Moon", "The Moon (↓)"),
    ("The Sun", "The Sun (↓)"),
    ("Aeon", "Aeon (↓)"),
    ("The Universe", "The Universe (↓)"),

    # WANDS
    ("Ace of Wands", "Ace of Wands (↓)"),
    ("Two of Wands", "Two of Wands (↓)"),
    ("Three of Wands", "Three of Wands (↓)"),
    ("Four of Wands", "Four of Wands (↓)"),
    ("Five of Wands", "Five of Wands (↓)"),
    ("Six of Wands", "Six of Wands (↓)"),
    ("Seven of Wands", "Seven of Wands (↓)"),
    ("Eight of Wands", "Eight of Wands (↓)"),
    ("Nine of Wands", "Nine of Wands (↓)"),
    ("Ten of Wands", "Ten of Wands (↓)"),
    ("Princess of Wands", "Princess of Wands (↓)"),
    ("Prince of Wands", "Prince of Wands (↓)"),
    ("Queen of Wands", "Queen of Wands (↓)"),
    ("King of Wands", "King of Wands (↓)"),

    # CUPS
    ("Ace of Cups", "Ace of Cups (↓)"),
    ("Two of Cups", "Two of Cups (↓)"),
    ("Three of Cups", "Three of Cups (↓)"),
    ("Four of Cups", "Four of Cups (↓)"),
    ("Five of Cups", "Five of Cups (↓)"),
    ("Six of Cups", "Six of Cups (↓)"),
    ("Seven of Cups", "Seven of Cups (↓)"),
    ("Eight of Cups", "Eight of Cups (↓)"),
    ("Nine of Cups", "Nine of Cups (↓)"),
    ("Ten of Cups", "Ten of Cups (↓)"),
    ("Princess of Cups", "Princess of Cups (↓)"),
    ("Prince of Cups", "Prince of Cups (↓)"),
    ("Queen of Cups", "Queen of Cups (↓)"),
    ("King of Cups", "King of Cups (↓)"),

    # SWORDS
    ("Ace of Swords", "Ace of Swords (↓)"),
    ("Two of Swords", "Two of Swords (↓)"),
    ("Three of Swords", "Three of Swords (↓)"),
    ("Four of Swords", "Four of Swords (↓)"),
    ("Five of Swords", "Five of Swords (↓)"),
    ("Six of Swords", "Six of Swords (↓)"),
    ("Seven of Swords", "Seven of Swords (↓)"),
    ("Eight of Swords", "Eight of Swords (↓)"),
    ("Nine of Swords", "Nine of Swords (↓)"),
    ("Ten of Swords", "Ten of Swords (↓)"),
    ("Princess of Swords", "Princess of Swords (↓)"),
    ("Prince of Swords", "Prince of Swords (↓)"),
    ("Queen of Swords", "Queen of Swords (↓)"),
    ("King of Swords", "King of Swords (↓)"),

    # COINS
    ("Ace of Coins", "Ace of Coins (↓)"),
    ("Two of Coins", "Two of Coins (↓)"),
    ("Three of Coins", "Three of Coins (↓)"),
    ("Four of Coins", "Four of Coins (↓)"),
    ("Five of Coins", "Five of Coins (↓)"),
    ("Six of Coins", "Six of Coins (↓)"),
    ("Seven of Coins", "Seven of Coins (↓)"),
    ("Eight of Coins", "Eight of Coins (↓)"),
    ("Nine of Coins", "Nine of Coins (↓)"),
    ("Ten of Coins", "Ten of Coins (↓)"),
    ("Princess of Coins", "Princess of Coins (↓)"),
    ("Prince of Coins", "Prince of Coins (↓)"),
    ("Queen of Coins", "Queen of Coins (↓)"),
    ("King of Coins", "King of Coins (↓)")
]
