nations = [
      ("Afghanistan.png", "Afghanistan"),
      ("Åland.png", "Åland"),
      ("Albania.png", "Albania"),
      ("Algeria.png", "Algeria"),
      ("American Samoa.png", "American Samoa"),
      ("Andorra.png", "Andorra"),
      ("Angola.png", "Angola"),
      ("Anguilla.png", "Anguilla"),
      ("Antigua and Barbuda.png", "Antigua and Barbuda"),
      ("Argentina.png", "Argentina"),
      ("Armenia.png", "Armenia"),
      ("Aruba.png", "Aruba"),
      ("Australia.png", "Australia"),
      ("Austria.png", "Austria"),
      ("Azerbaijan.png", "Azerbaijan"),
      ("Bahamas.png", "Bahamas"),
      ("Bahrain.png", "Bahrain"),
      ("Bangladesh.png", "Bangladesh"),
      ("Barbados.png", "Barbados"),
      ("Belarus.png", "Belarus"),
      ("Belgium (civil).png", "Belgium (civil)"),
      ("Belize.png", "Belize"),
      ("Benin.png", "Benin"),
      ("Bermuda.png", "Bermuda"),
      ("Bhutan.png", "Bhutan"),
      ("Bolivia.png", "Bolivia"),
      ("Bosnia and Herzegovina.png", "Bosnia and Herzegovina"),
      ("Botswana.png", "Botswana"),
      ("Brazil.png", "Brazil"),
      ("British Honduras (1919-1981).png", "British Honduras (1919-1981)"),
      ("British Virgin Islands.png", "British Virgin Islands"),
      ("Brunei.png", "Brunei"),
      ("Bulgaria.png", "Bulgaria"),
      ("Burkina Faso.png", "Burkina Faso"),
      ("Burundi.png", "Burundi"),
      ("Cambodia.png", "Cambodia"),
      ("Cameroon.png", "Cameroon"),
      ("Canada (Pantone).png", "Canada (Pantone)"),
      ("Cape Verde.png", "Cape Verde"),
      ("Cayman Islands.png", "Cayman Islands"),
      ("Central African Republic.png", "Central African Republic"),
      ("Ceylon (1948-1951).png", "Ceylon (1948-1951)"),
      ("Chad.png", "Chad"),
      ("Chile.png", "Chile"),
      ("Chinese Taipei for Olympic games.png", "Chinese Taipei for Olympic games"),
      ("Christmas Island.png", "Christmas Island"),
      ("Cocos (Keeling) Islands.png", "Cocos (Keeling) Islands"),
      ("Colombia.png", "Colombia"),
      ("Commissioner of the British Indian Ocean Territory.png", "Commissioner of the British Indian Ocean Territory"),
      ("Comoros.png", "Comoros"),
      ("Cook Islands.png", "Cook Islands"),
      ("Costa Rica.png", "Costa Rica"),
      ("Croatia.png", "Croatia"),
      ("Cuba.png", "Cuba"),
      ("Cura‡ao.png", "Cura‡ao"),
      ("Cyprus.png", "Cyprus"),
      ("Czech Republic.png", "Czech Republic"),
      ("C“te d'Ivoire.png", "C“te d'Ivoire"),
      ("Democratic Republic of the Congo.png", "Democratic Republic of the Congo"),
      ("Denmark.png", "Denmark"),
      ("Djibouti.png", "Djibouti"),
      ("Dominica.png", "Dominica"),
      ("Dominican Republic.png", "Dominican Republic"),
      ("East Germany.png", "East Germany"),
      ("East Timor.png", "East Timor"),
      ("Ecuador.png", "Ecuador"),
      ("Egypt.png", "Egypt"),
      ("El Salvador.png", "El Salvador"),
      ("England.png", "England"),
      ("Equatorial Guinea.png", "Equatorial Guinea"),
      ("Eritrea.png", "Eritrea"),
      ("Estonia.png", "Estonia"),
      ("Eswatini.png", "Eswatini"),
      ("Ethiopia.png", "Ethiopia"),
      ("Falkland Islands.png", "Falkland Islands"),
      ("Faroe Islands.png", "Faroe Islands"),
      ("Federated States of Micronesia.png", "Federated States of Micronesia"),
      ("Fiji.png", "Fiji"),
      ("Finland.png", "Finland"),
      ("France.png", "France"),
      ("French Polynesia.png", "French Polynesia"),
      ("French Southern and Antarctic Lands.png", "French Southern and Antarctic Lands"),
      ("Gabon.png", "Gabon"),
      ("Gambia.png", "Gambia"),
      ("Georgia.png", "Georgia"),
      ("Germany.png", "Germany"),
      ("Ghana.png", "Ghana"),
      ("Gibraltar.png", "Gibraltar"),
      ("Greece.png", "Greece"),
      ("Greenland.png", "Greenland"),
      ("Grenada.png", "Grenada"),
      ("Guam.png", "Guam"),
      ("Guatemala.png", "Guatemala"),
      ("Guernsey.png", "Guernsey"),
      ("Guinea-Bissau.png", "Guinea-Bissau"),
      ("Guinea.png", "Guinea"),
      ("Guyana.png", "Guyana"),
      ("Haiti.png", "Haiti"),
      ("Honduras (2008 Olympics).png", "Honduras (2008 Olympics)"),
      ("Hong Kong.png", "Hong Kong"),
      ("Hungary.png", "Hungary"),
      ("India.png", "India"),
      ("Indonesia.png", "Indonesia"),
      ("Iran.png", "Iran"),
      ("Iraq.png", "Iraq"),
      ("Ireland.png", "Ireland"),
      ("Isle of Man.png", "Isle of Man"),
      ("Italy.png", "Italy"),
      ("Jamaica.png", "Jamaica"),
      ("Japan.png", "Japan"),
      ("Jersey.png", "Jersey"),
      ("Jordan.png", "Jordan"),
      ("Kazakhstan.png", "Kazakhstan"),
      ("Kenya.png", "Kenya"),
      ("Khmer Republic.png", "Khmer Republic"),
      ("Kiribati.png", "Kiribati"),
      ("Kosovo.png", "Kosovo"),
      ("Kuwait.png", "Kuwait"),
      ("Kyrgyzstan.png", "Kyrgyzstan"),
      ("Laos.png", "Laos"),
      ("Latvia.png", "Latvia"),
      ("Lebanon.png", "Lebanon"),
      ("Lesotho.png", "Lesotho"),
      ("Liberia.png", "Liberia"),
      ("Libya.png", "Libya"),
      ("Liechtenstein.png", "Liechtenstein"),
      ("Lithuania.png", "Lithuania"),
      ("Luxembourg.png", "Luxembourg"),
      ("Macau.png", "Macau"),
      ("Madagascar.png", "Madagascar"),
      ("Malawi.png", "Malawi"),
      ("Malaya.png", "Malaya"),
      ("Malaysia.png", "Malaysia"),
      ("Maldives.png", "Maldives"),
      ("Mali.png", "Mali"),
      ("Malta.png", "Malta"),
      ("Marshall Islands.png", "Marshall Islands"),
      ("Mauritania.png", "Mauritania"),
      ("Mauritius.png", "Mauritius"),
      ("Mayotte (local).png", "Mayotte (local)"),
      ("Mexico.png", "Mexico"),
      ("Moldova.png", "Moldova"),
      ("Monaco.png", "Monaco"),
      ("Mongolia.png", "Mongolia"),
      ("Montenegro.png", "Montenegro"),
      ("Montserrat.png", "Montserrat"),
      ("Morocco.png", "Morocco"),
      ("Mozambique.png", "Mozambique"),
      ("Myanmar (1974-2010).png", "Myanmar (1974-2010)"),
      ("Myanmar.png", "Myanmar"),
      ("Namibia.png", "Namibia"),
      ("Nauru.png", "Nauru"),
      ("Nepal.png", "Nepal"),
      ("Netherlands Antilles (1986-2010).png", "Netherlands Antilles (1986-2010)"),
      ("Netherlands.png", "Netherlands"),
      ("New Caledonia.png", "New Caledonia"),
      ("New Zealand.png", "New Zealand"),
      ("Nicaragua.png", "Nicaragua"),
      ("Niger.png", "Niger"),
      ("Nigeria.png", "Nigeria"),
      ("Niue.png", "Niue"),
      ("Norfolk Island.png", "Norfolk Island"),
      ("North Borneo (1902-1946).png", "North Borneo (1902-1946)"),
      ("North Korea.png", "North Korea"),
      ("North Macedonia.png", "North Macedonia"),
      ("North Vietnam (1955-1975).png", "North Vietnam (1955-1975)"),
      ("North Yemen.png", "North Yemen"),
      ("Northern Mariana Islands.png", "Northern Mariana Islands"),
      ("Northern Rhodesia (1939-1964).png", "Northern Rhodesia (1939-1964)"),
      ("Norway.png", "Norway"),
      ("Oman.png", "Oman"),
      ("Pakistan.png", "Pakistan"),
      ("Palau.png", "Palau"),
      ("Palestine.png", "Palestine"),
      ("Panama.png", "Panama"),
      ("Papua New Guinea.png", "Papua New Guinea"),
      ("Paraguay.png", "Paraguay"),
      ("People's Republic of China.png", "People's Republic of China"),
      ("Peru.png", "Peru"),
      ("Philippines.png", "Philippines"),
      ("Pitcairn Islands.png", "Pitcairn Islands"),
      ("Poland.png", "Poland"),
      ("Portugal.png", "Portugal"),
      ("Puerto Rico.png", "Puerto Rico"),
      ("Qatar.png", "Qatar"),
      ("Republic of China.png", "Republic of China"),
      ("Republic of the Congo.png", "Republic of the Congo"),
      ("Rhodesia (1968-1979).png", "Rhodesia (1968-1979)"),
      ("Romania.png", "Romania"),
      ("Russia.png", "Russia"),
      ("Rwanda.png", "Rwanda"),
      ("Saint Kitts and Nevis.png", "Saint Kitts and Nevis"),
      ("Saint Lucia.png", "Saint Lucia"),
      ("Saint Vincent and the Grenadines.png", "Saint Vincent and the Grenadines"),
      ("Saint-Pierre and Miquelon.png", "Saint-Pierre and Miquelon"),
      ("Samoa.png", "Samoa"),
      ("San Marino.png", "San Marino"),
      ("Sao Tome and Principe.png", "Sao Tome and Principe"),
      ("Saudi Arabia.png", "Saudi Arabia"),
      ("Scotland.png", "Scotland"),
      ("Senegal.png", "Senegal"),
      ("Serbia.png", "Serbia"),
      ("Serbia and Montenegro (2003–2006).png", "Serbia and Montenegro (2003–2006)"),
      ("Zaire.png", "Zaire"),
      ("Seychelles.png", "Seychelles"),
      ("Sierra Leone.png", "Sierra Leone"),
      ("Singapore.png", "Singapore"),
      ("Sint Maarten.png", "Sint Maarten"),
      ("Slovakia.png", "Slovakia"),
      ("Slovenia.png", "Slovenia"),
      ("Solomon Islands.png", "Solomon Islands"),
      ("Somalia.png", "Somalia"),
      ("South Africa.png", "South Africa"),
      ("South Georgia and the South Sandwich Islands.png", "South Georgia and the South Sandwich Islands"),
      ("South Korea.png", "South Korea"),
      ("South Sudan.png", "South Sudan"),
      ("South Vietnam.png", "South Vietnam"),
      ("South Yemen.png", "South Yemen"),
      ("Soviet Union.png", "Soviet Union"),
      ("Spain.png", "Spain"),
      ("Sri Lanka.png", "Sri Lanka"),
      ("Sudan.png", "Sudan"),
      ("Suriname.png", "Suriname"),
      ("Sweden.png", "Sweden"),
      ("Switzerland.png", "Switzerland"),
      ("Syria.png", "Syria"),
      ("Tajikistan.png", "Tajikistan"),
      ("Tanzania.png", "Tanzania"),
      ("Thailand.png", "Thailand"),
      ("Togo.png", "Togo"),
      ("Tokelau.png", "Tokelau"),
      ("Tonga.png", "Tonga"),
      ("Trinidad and Tobago.png", "Trinidad and Tobago"),
      ("Tunisia.png", "Tunisia"),
      ("Turkey.png", "Turkey"),
      ("Turkmenistan.png", "Turkmenistan"),
      ("Turks and Caicos Islands.png", "Turks and Caicos Islands"),
      ("Tuvalu.png", "Tuvalu"),
      ("Uganda.png", "Uganda"),
      ("Ukraine.png", "Ukraine"),
      ("Ulster Banner.png", "Ulster Banner"),
      ("United Arab Emirates.png", "United Arab Emirates"),
      ("United Kingdom.png", "United Kingdom"),
      ("United States Virgin Islands.png", "United States Virgin Islands"),
      ("United States.png", "United States"),
      ("Upper Volta.png", "Upper Volta"),
      ("Uruguay.png", "Uruguay"),
      ("Uzbekistan.png", "Uzbekistan"),
      ("Vanuatu.png", "Vanuatu"),
      ("Vatican City.png", "Vatican City"),
      ("Venezuela.png", "Venezuela"),
      ("Vietnam.png", "Vietnam"),
      ("Wales (1959-present).png", "Wales (1959-present)"),
      ("Yemen.png", "Yemen"),
      ("Yugoslavia (1946-1992).png", "Yugoslavia (1946-1992)"),
      ("Yugoslavia (1992–2003).png", "Yugoslavia (1992–2003)"),
      ("Zambia.png", "Zambia"),
      ("Zimbabwe.png", "Zimbabwe")
]
